# Generated by Django 3.2.25 on 2024-05-12 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_petitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
